-- Create task_categories table if it doesn't exist
CREATE TABLE IF NOT EXISTS task_categories (
    id INT AUTO_INCREMENT PRIMARY KEY,
    department_name VARCHAR(100) NOT NULL,
    category_name VARCHAR(100) NOT NULL,
    description TEXT DEFAULT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY unique_dept_category (department_name, category_name)
);

-- Clear existing categories
DELETE FROM task_categories;

-- Insert comprehensive task categories from original system
INSERT IGNORE INTO task_categories (department_name, category_name, description) VALUES
-- Liaison Department Categories
('Liaison', 'Document Collection', 'Gathering required documents from clients'),
('Liaison', 'Portal Upload', 'Uploading details in government portals'),
('Liaison', 'Documentation', 'Document preparation and verification'),
('Liaison', 'Follow-up', 'Client and government office follow-ups'),
('Liaison', 'Document Submission', 'Physical document submission'),
('Liaison', 'Courier Services', 'Document dispatch and delivery'),
('Liaison', 'Client Meeting', 'Client consultation and meetings'),
('Liaison', 'Government Office Visit', 'Official visits and submissions'),
-- Human Resources Categories
('Human Resources', 'Recruitment', 'Hiring and recruitment activities'),
('Human Resources', 'Training', 'Employee training and development'),
('Human Resources', 'Performance Review', 'Employee performance evaluations'),
('Human Resources', 'Policy Development', 'HR policy creation and updates'),
('Human Resources', 'Employee Relations', 'Managing employee relations and issues'),
('Human Resources', 'Compliance', 'HR compliance and regulatory tasks'),
-- Operations Categories
('Operations', 'Process Improvement', 'Improving operational processes'),
('Operations', 'Quality Control', 'Quality assurance and control'),
('Operations', 'Vendor Management', 'Managing vendor relationships'),
('Operations', 'Inventory Management', 'Managing inventory and supplies'),
('Operations', 'Logistics', 'Logistics and supply chain management'),
('Operations', 'Facility Management', 'Managing office facilities'),
-- Finance & Accounts Categories
('Finance & Accounts', 'Ledger Update', 'General ledger maintenance and updates'),
('Finance & Accounts', 'Invoice Creation', 'Customer invoice generation'),
('Finance & Accounts', 'Quotation Creation', 'Price quotation preparation'),
('Finance & Accounts', 'PO Creation', 'Purchase order generation'),
('Finance & Accounts', 'PO Follow-up', 'Purchase order tracking and follow-up'),
('Finance & Accounts', 'Payment Follow-up', 'Outstanding payment collection'),
('Finance & Accounts', 'Ledger Follow-up', 'Account reconciliation and follow-up'),
('Finance & Accounts', 'GST Follow-up', 'GST compliance and filing'),
('Finance & Accounts', 'Mail Checking', 'Email correspondence and communication'),
('Finance & Accounts', 'Financial Reporting', 'Monthly and quarterly reports'),
('Finance & Accounts', 'Accounting', 'General accounting and bookkeeping'),
('Finance & Accounts', 'Budgeting', 'Budget planning and management'),
('Finance & Accounts', 'Financial Analysis', 'Financial data analysis and reporting'),
('Finance & Accounts', 'Audit', 'Internal and external audit activities'),
('Finance & Accounts', 'Tax Planning', 'Tax preparation and planning'),
('Finance & Accounts', 'Invoice Processing', 'Processing invoices and payments'),
('Finance & Accounts', 'Bank Reconciliation', 'Bank account reconciliation'),
('Finance & Accounts', 'Expense Tracking', 'Expense monitoring and analysis'),
('Finance & Accounts', 'Petty Cash Management', 'Petty cash handling'),
('Finance & Accounts', 'Vendor Payment', 'Vendor payment processing'),
('Finance & Accounts', 'Customer Payment Processing', 'Customer payment handling'),
('Finance & Accounts', 'Cash Flow Management', 'Cash flow planning and monitoring'),
('Finance & Accounts', 'Investment Analysis', 'Investment evaluation and analysis'),
('Finance & Accounts', 'Cost Analysis', 'Cost evaluation and optimization'),
('Finance & Accounts', 'GST Filing', 'GST return preparation and filing'),
('Finance & Accounts', 'TDS Processing', 'TDS calculation and filing'),
('Finance & Accounts', 'Loan Management', 'Loan processing and management'),
('Finance & Accounts', 'Asset Management', 'Asset tracking and management'),
-- Information Technology Categories
('Information Technology', 'Development', 'Software development and coding tasks'),
('Information Technology', 'Testing', 'Quality assurance and testing activities'),
('Information Technology', 'Bug Fixing', 'Error resolution and debugging'),
('Information Technology', 'Planning', 'Project planning and architecture'),
('Information Technology', 'Hosting', 'Server management and deployment'),
('Information Technology', 'Maintenance', 'System maintenance and updates'),
('Information Technology', 'Documentation', 'Technical documentation and guides'),
('Information Technology', 'Code Review', 'Peer code review and quality checks'),
('Information Technology', 'Deployment', 'Application deployment and release'),
('Information Technology', 'System Analysis', 'System analysis and design'),
('Information Technology', 'Database Design', 'Database design and optimization'),
('Information Technology', 'API Development', 'API development and integration'),
('Information Technology', 'Frontend Development', 'Frontend development tasks'),
('Information Technology', 'Backend Development', 'Backend development tasks'),
('Information Technology', 'DevOps', 'DevOps and automation tasks'),
('Information Technology', 'Cloud Management', 'Cloud infrastructure management'),
('Information Technology', 'Security Implementation', 'Security implementation and monitoring'),
('Information Technology', 'System Administration', 'System administration tasks'),
('Information Technology', 'Database Management', 'Database administration'),
('Information Technology', 'Security Updates', 'Security patches and updates'),
('Information Technology', 'Backup Management', 'Data backup and recovery'),
('Information Technology', 'Network Management', 'Network administration'),
('Information Technology', 'User Support', 'Technical user support'),
('Information Technology', 'Software Installation', 'Software installation and configuration'),
('Information Technology', 'Hardware Maintenance', 'Hardware maintenance and repair'),
('Information Technology', 'Performance Monitoring', 'System performance monitoring'),
-- Marketing & Sales Categories
('Marketing & Sales', 'Campaign Planning', 'Marketing campaign strategy and planning'),
('Marketing & Sales', 'Content Creation', 'Marketing content and material creation'),
('Marketing & Sales', 'Social Media Management', 'Social media posts and engagement'),
('Marketing & Sales', 'Lead Generation', 'Prospecting and lead identification'),
('Marketing & Sales', 'Client Presentation', 'Sales presentations and proposals'),
('Marketing & Sales', 'Market Research', 'Industry and competitor analysis'),
('Marketing & Sales', 'Event Planning', 'Marketing events and webinars'),
('Marketing & Sales', 'Email Marketing', 'Email campaigns and newsletters'),
('Marketing & Sales', 'Client Meeting', 'Meeting with clients and prospects'),
('Marketing & Sales', 'Proposal Writing', 'Creating sales proposals and quotes'),
('Marketing & Sales', 'Customer Support', 'Supporting existing customers'),
('Marketing & Sales', 'Brand Management', 'Brand development and management'),
('Marketing & Sales', 'Digital Marketing', 'Digital marketing campaigns'),
('Marketing & Sales', 'SEO/SEM', 'Search engine optimization and marketing'),
('Marketing & Sales', 'Public Relations', 'Public relations and communications'),
('Marketing & Sales', 'Customer Surveys', 'Customer feedback and surveys'),
('Marketing & Sales', 'Competitor Analysis', 'Competitive analysis and research'),
('Marketing & Sales', 'Product Promotion', 'Product promotion and marketing'),
('Marketing & Sales', 'Sales Presentation', 'Sales presentation development'),
('Marketing & Sales', 'Deal Negotiation', 'Deal negotiation and closing'),
('Marketing & Sales', 'Customer Onboarding', 'New customer onboarding'),
('Marketing & Sales', 'Account Management', 'Existing account management'),
('Marketing & Sales', 'Sales Reporting', 'Sales performance reporting'),
('Marketing & Sales', 'CRM Management', 'CRM system management'),
('Marketing & Sales', 'Territory Management', 'Sales territory management'),
('Marketing & Sales', 'Product Demo', 'Product demonstration'),
('Marketing & Sales', 'Contract Management', 'Contract negotiation and management');