CREATE TABLE IF NOT EXISTS `daily_planner` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `date` date NOT NULL,
  `task_id` int(11) DEFAULT NULL,
  `task_type` varchar(50) DEFAULT 'personal',
  `title` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `planned_start_time` time DEFAULT NULL,
  `planned_duration` int(11) DEFAULT 60,
  `priority_order` int(11) DEFAULT 1,
  `status` varchar(20) DEFAULT 'planned',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `task_id` (`task_id`),
  KEY `date` (`date`),
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  FOREIGN KEY (`task_id`) REFERENCES `tasks` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;