<?php
$title = 'Daily Planner';
$active_page = 'planner';

ob_start();
?>

<div class="page-header">
    <div class="page-title">
        <h1><span>📅</span> Daily Planner</h1>
        <p>Plan and organize your daily activities and tasks</p>
    </div>
    <div class="page-actions">
        <button class="btn btn--primary" onclick="showCreatePlanModal()">
            <span>➕</span> Add Plan
        </button>
        <button class="btn btn--secondary" onclick="toggleView()" id="viewToggleBtn">
            📅 Calendar View
        </button>
    </div>
</div>

<div class="dashboard-grid">
    <div class="kpi-card">
        <div class="kpi-card__header">
            <div class="kpi-card__icon">📅</div>
            <div class="kpi-card__trend">↗ +5%</div>
        </div>
        <div class="kpi-card__value"><?= count($data['plans']) ?></div>
        <div class="kpi-card__label">Total Plans</div>
        <div class="kpi-card__status">Active</div>
    </div>
    
    <div class="kpi-card">
        <div class="kpi-card__header">
            <div class="kpi-card__icon">✅</div>
            <div class="kpi-card__trend">↗ +3%</div>
        </div>
        <div class="kpi-card__value"><?= count(array_filter($data['plans'], function($p) { return date('Y-m-d', strtotime($p['plan_date'])) === date('Y-m-d'); })) ?></div>
        <div class="kpi-card__label">Today's Plans</div>
        <div class="kpi-card__status">Scheduled</div>
    </div>
    
    <div class="kpi-card">
        <div class="kpi-card__header">
            <div class="kpi-card__icon">📊</div>
            <div class="kpi-card__trend">↗ +8%</div>
        </div>
        <div class="kpi-card__value"><?= count(array_filter($data['plans'], function($p) { return date('Y-m-d', strtotime($p['plan_date'])) >= date('Y-m-d') && date('Y-m-d', strtotime($p['plan_date'])) <= date('Y-m-d', strtotime('+7 days')); })) ?></div>
        <div class="kpi-card__label">This Week</div>
        <div class="kpi-card__status">Upcoming</div>
    </div>
</div>

<div class="planner-layout">
    <div class="planner-sidebar">
        <div class="card">
            <div class="card__header">
                <h3 class="card__title">
                    <span>📋</span> Quick Actions
                </h3>
            </div>
            <div class="card__body">
                <button class="btn btn--block btn--primary" onclick="showCreatePlanModal()">
                    <span>➕</span> New Plan
                </button>
                <button class="btn btn--block btn--secondary" onclick="filterPlans('today')">
                    <span>📅</span> Today's Plans
                </button>
                <button class="btn btn--block btn--secondary" onclick="filterPlans('week')">
                    <span>📊</span> This Week
                </button>
                <button class="btn btn--block btn--secondary" onclick="filterPlans('all')">
                    <span>🗂️</span> All Plans
                </button>
            </div>
        </div>
    </div>
    
    <div class="planner-main">
        <!-- Calendar View -->
        <div id="calendarView" class="ergon-calendar" style="display: none;">
            <div class="ergon-calendar__header">
                <button class="btn btn--secondary" onclick="previousMonth()">‹</button>
                <h3 class="ergon-calendar__title" id="calendarTitle">January 2024</h3>
                <button class="btn btn--secondary" onclick="nextMonth()">›</button>
            </div>
            <div class="ergon-calendar__body">
                <div class="ergon-calendar__weekdays">
                    <div class="ergon-calendar__weekday">Sun</div>
                    <div class="ergon-calendar__weekday">Mon</div>
                    <div class="ergon-calendar__weekday">Tue</div>
                    <div class="ergon-calendar__weekday">Wed</div>
                    <div class="ergon-calendar__weekday">Thu</div>
                    <div class="ergon-calendar__weekday">Fri</div>
                    <div class="ergon-calendar__weekday">Sat</div>
                </div>
                <div class="ergon-calendar__days" id="calendarDays">
                    <!-- Calendar days will be generated by JavaScript -->
                </div>
            </div>
        </div>
        
        <!-- List View -->
        <div id="listView" class="card">
            <div class="card__header">
                <h2 class="card__title">
                    <span>📅</span> My Daily Plans
                </h2>
            </div>
            <div class="card__body">
                <?php if (empty($data['plans'])): ?>
                    <div class="empty-state">
                        <div class="empty-icon">📅</div>
                        <h3>No Plans Yet</h3>
                        <p>Start planning your day by creating your first plan.</p>
                        <button class="btn btn--primary" onclick="showCreatePlanModal()">
                            <span>➕</span> Create First Plan
                        </button>
                    </div>
                <?php else: ?>
                    <div class="plans-grid" id="plansGrid">
                        <?php foreach ($data['plans'] as $plan): ?>
                        <div class="plan-card" data-date="<?= date('Y-m-d', strtotime($plan['plan_date'])) ?>">
                            <div class="plan-header">
                                <div class="plan-date">
                                    <div class="plan-day"><?= date('d', strtotime($plan['plan_date'])) ?></div>
                                    <div class="plan-month"><?= date('M', strtotime($plan['plan_date'])) ?></div>
                                </div>
                                <div class="plan-actions">
                                    <button class="btn btn--sm btn--secondary" onclick="editPlan(<?= $plan['id'] ?>)">
                                        <span>✏️</span>
                                    </button>
                                    <button class="btn btn--sm btn--danger" onclick="deletePlan(<?= $plan['id'] ?>)">
                                        <span>🗑️</span>
                                    </button>
                                </div>
                            </div>
                            <div class="plan-content">
                                <h4 class="plan-title"><?= htmlspecialchars($plan['title']) ?></h4>
                                <p class="plan-description"><?= htmlspecialchars($plan['description']) ?></p>
                            </div>
                            <div class="plan-footer">
                                <span class="plan-time"><?= date('g:i A', strtotime($plan['plan_date'])) ?></span>
                                <span class="plan-status <?= date('Y-m-d', strtotime($plan['plan_date'])) < date('Y-m-d') ? 'status-past' : (date('Y-m-d', strtotime($plan['plan_date'])) === date('Y-m-d') ? 'status-today' : 'status-future') ?>">
                                    <?= date('Y-m-d', strtotime($plan['plan_date'])) < date('Y-m-d') ? 'Past' : (date('Y-m-d', strtotime($plan['plan_date'])) === date('Y-m-d') ? 'Today' : 'Upcoming') ?>
                                </span>
                            </div>
                        </div>
                        <?php endforeach; ?>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>

<!-- Enhanced Create Plan Modal -->
<div class="modal" id="createPlanModal">
    <div class="modal-content modal-content--large">
        <div class="modal-header">
            <h3><span>📅</span> Create New Plan</h3>
            <button class="modal-close" onclick="closeModal('createPlanModal')">&times;</button>
        </div>
        <form method="POST" action="/ergon/planner/create">
            <div class="modal-body">
                <div class="form-row">
                    <div class="form-group">
                        <label class="form-label">Plan Title *</label>
                        <input type="text" name="title" class="form-control" required placeholder="Enter plan title">
                    </div>
                    <div class="form-group">
                        <label class="form-label">Plan Type *</label>
                        <select name="plan_type" class="form-control" required>
                            <option value="">Select Type</option>
                            <option value="meeting">📋 Meeting</option>
                            <option value="task">✅ Task</option>
                            <option value="appointment">🤝 Appointment</option>
                            <option value="reminder">⏰ Reminder</option>
                            <option value="event">🎉 Event</option>
                            <option value="call">📞 Call</option>
                            <option value="training">📚 Training</option>
                            <option value="review">🔍 Review</option>
                        </select>
                    </div>
                </div>
                
                <div class="form-group">
                    <label class="form-label">Description</label>
                    <textarea name="description" class="form-control" rows="3" placeholder="Describe your plan in detail"></textarea>
                </div>
                
                <div class="form-row">
                    <div class="form-group">
                        <label class="form-label">Priority *</label>
                        <select name="priority" class="form-control" required>
                            <option value="low">🟢 Low</option>
                            <option value="medium" selected>🟡 Medium</option>
                            <option value="high">🟠 High</option>
                            <option value="urgent">🔴 Urgent</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="form-label">Status</label>
                        <select name="status" class="form-control">
                            <option value="planned" selected>📋 Planned</option>
                            <option value="in_progress">⏳ In Progress</option>
                            <option value="completed">✅ Completed</option>
                            <option value="cancelled">❌ Cancelled</option>
                        </select>
                    </div>
                </div>
                
                <div class="form-row">
                    <div class="form-group">
                        <label class="form-label">Start Date & Time *</label>
                        <input type="datetime-local" name="start_date" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label class="form-label">End Date & Time</label>
                        <input type="datetime-local" name="end_date" class="form-control">
                    </div>
                </div>
                
                <div class="form-row">
                    <div class="form-group">
                        <label class="form-label">Location</label>
                        <input type="text" name="location" class="form-control" placeholder="Meeting room, address, online link">
                    </div>
                    <div class="form-group">
                        <label class="form-label">Duration (minutes)</label>
                        <input type="number" name="duration" class="form-control" placeholder="60" min="15" max="480">
                    </div>
                </div>
                
                <div class="form-group">
                    <label class="form-label">Participants/Attendees</label>
                    <textarea name="participants" class="form-control" rows="2" placeholder="Enter participant names or email addresses (one per line)"></textarea>
                </div>
                
                <div class="form-row">
                    <div class="form-group">
                        <label class="form-label">Category</label>
                        <select name="category" class="form-control">
                            <option value="work">💼 Work</option>
                            <option value="personal">👤 Personal</option>
                            <option value="client">🤝 Client</option>
                            <option value="internal">🏢 Internal</option>
                            <option value="training">📚 Training</option>
                            <option value="project">📊 Project</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="form-label">Reminder</label>
                        <select name="reminder" class="form-control">
                            <option value="none">No Reminder</option>
                            <option value="5">5 minutes before</option>
                            <option value="15" selected>15 minutes before</option>
                            <option value="30">30 minutes before</option>
                            <option value="60">1 hour before</option>
                            <option value="1440">1 day before</option>
                            <option value="10080">1 week before</option>
                        </select>
                    </div>
                </div>
                
                <div class="form-row">
                    <div class="form-group">
                        <label class="form-label">Assigned To</label>
                        <select name="assigned_to" class="form-control">
                            <option value="">Select User</option>
                            <option value="self" selected>Myself</option>
                            <option value="team">Team</option>
                            <option value="admin">Admin</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="form-label">Recurring</label>
                        <select name="recurring" class="form-control">
                            <option value="none" selected>No Repeat</option>
                            <option value="daily">Daily</option>
                            <option value="weekly">Weekly</option>
                            <option value="monthly">Monthly</option>
                            <option value="yearly">Yearly</option>
                        </select>
                    </div>
                </div>
                
                <div class="form-group">
                    <label class="form-label">Notes/Additional Information</label>
                    <textarea name="notes" class="form-control" rows="2" placeholder="Any additional notes or requirements"></textarea>
                </div>
                
                <div class="form-group">
                    <label class="form-label">Tags</label>
                    <input type="text" name="tags" class="form-control" placeholder="Enter tags separated by commas (e.g., important, client-meeting, urgent)">
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn--secondary" onclick="closeModal('createPlanModal')">Cancel</button>
                <button type="submit" class="btn btn--primary">Create Plan</button>
            </div>
        </form>
    </div>
</div>

<script>
let currentView = 'list';
let currentDate = new Date();

function showCreatePlanModal() {
    document.getElementById('createPlanModal').style.display = 'block';
}

function closeModal(modalId) {
    document.getElementById(modalId).style.display = 'none';
}

// Sample plans data for calendar display
const samplePlans = [
    { id: 1, title: 'Team Meeting', plan_date: '2024-01-15T10:00:00', priority: 'high' },
    { id: 2, title: 'Client Call', plan_date: '2024-01-18T14:30:00', priority: 'medium' },
    { id: 3, title: 'Project Review', plan_date: '2024-01-22T09:00:00', priority: 'low' },
    { id: 4, title: 'Training Session', plan_date: '2024-01-25T11:00:00', priority: 'medium' }
];

function toggleView() {
    const calendarView = document.getElementById('calendarView');
    const listView = document.getElementById('listView');
    const viewToggleBtn = document.getElementById('viewToggleBtn');
    
    if (currentView === 'list') {
        calendarView.style.display = 'block';
        listView.style.display = 'none';
        viewToggleBtn.innerHTML = '📋 List View';
        currentView = 'calendar';
        generateCalendar();
    } else {
        calendarView.style.display = 'none';
        listView.style.display = 'block';
        viewToggleBtn.innerHTML = '📅 Calendar View';
        currentView = 'list';
    }
}

function generateCalendar() {
    const calendarDays = document.getElementById('calendarDays');
    const calendarTitle = document.getElementById('calendarTitle');
    
    const year = currentDate.getFullYear();
    const month = currentDate.getMonth();
    
    calendarTitle.textContent = new Date(year, month).toLocaleDateString('en-US', { month: 'long', year: 'numeric' });
    
    const firstDay = new Date(year, month, 1).getDay();
    const daysInMonth = new Date(year, month + 1, 0).getDate();
    
    let html = '';
    
    // Empty cells for days before month starts
    for (let i = 0; i < firstDay; i++) {
        html += '<div class="ergon-calendar__day ergon-calendar__day--empty"></div>';
    }
    
    // Days of the month
    for (let day = 1; day <= daysInMonth; day++) {
        const currentDateStr = `${year}-${String(month + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
        const isToday = new Date().toDateString() === new Date(year, month, day).toDateString();
        const dayClass = isToday ? 'ergon-calendar__day ergon-calendar__day--today' : 'ergon-calendar__day';
        
        // Find plans for this day
        const dayPlans = samplePlans.filter(plan => {
            const planDate = new Date(plan.plan_date);
            return planDate.getFullYear() === year && 
                   planDate.getMonth() === month && 
                   planDate.getDate() === day;
        });
        
        let eventsHtml = '';
        dayPlans.forEach(plan => {
            const priorityColor = plan.priority === 'high' ? '#dc2626' : 
                                plan.priority === 'medium' ? '#d97706' : '#059669';
            eventsHtml += `<div class="calendar-event" style="background: ${priorityColor}; color: white; font-size: 10px; padding: 2px 4px; margin: 1px 0; border-radius: 3px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;">${plan.title}</div>`;
        });
        
        html += `<div class="${dayClass}" onclick="selectDate(${year}, ${month}, ${day})">
            <div class="ergon-calendar__day-number">${day}</div>
            <div class="ergon-calendar__events">
                ${eventsHtml}
            </div>
        </div>`;
    }
    
    calendarDays.innerHTML = html;
}

function previousMonth() {
    currentDate.setMonth(currentDate.getMonth() - 1);
    generateCalendar();
}

function nextMonth() {
    currentDate.setMonth(currentDate.getMonth() + 1);
    generateCalendar();
}

function selectDate(year, month, day) {
    const selectedDate = new Date(year, month, day);
    showCreatePlanModal();
    // Pre-fill the date in the modal
    const startDateInput = document.querySelector('input[name="start_date"]');
    if (startDateInput) {
        const dateStr = `${year}-${String(month + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}T09:00`;
        startDateInput.value = dateStr;
    }
}

function filterPlans(filter) {
    const plans = document.querySelectorAll('.plan-card');
    const today = new Date().toISOString().split('T')[0];
    
    plans.forEach(plan => {
        const planDate = plan.dataset.date;
        let show = true;
        
        switch(filter) {
            case 'today':
                show = planDate === today;
                break;
            case 'week':
                const weekFromNow = new Date(Date.now() + 7 * 86400000).toISOString().split('T')[0];
                show = planDate >= today && planDate <= weekFromNow;
                break;
            case 'all':
                show = true;
                break;
        }
        
        plan.style.display = show ? 'block' : 'none';
    });
}

function editPlan(planId) {
    console.log('Edit plan:', planId);
}

function deletePlan(planId) {
    if (confirm('Are you sure you want to delete this plan?')) {
        console.log('Delete plan:', planId);
    }
}

// Initialize calendar on page load
document.addEventListener('DOMContentLoaded', function() {
    generateCalendar();
});
</script>

<?php
$content = ob_get_clean();
include __DIR__ . '/../layouts/dashboard.php';
?>
