-- Drop existing tables
DROP TABLE IF EXISTS finance_customers;
DROP TABLE IF EXISTS finance_invoices;
DROP TABLE IF EXISTS finance_payments;
DROP TABLE IF EXISTS finance_purchase_orders;
DROP TABLE IF EXISTS finance_quotations;

-- Create tables matching PostgreSQL structure exactly

CREATE TABLE finance_customer (
  id BIGINT PRIMARY KEY,
  customer_code VARCHAR(255),
  customer_type VARCHAR(255),
  name VARCHAR(255),
  display_name VARCHAR(255),
  email VARCHAR(255),
  phone VARCHAR(255),
  mobile VARCHAR(255),
  website VARCHAR(255),
  billing_address_line1 VARCHAR(255),
  billing_address_line2 VARCHAR(255),
  billing_city VARCHAR(255),
  billing_state VARCHAR(255),
  billing_pincode VARCHAR(255),
  billing_country VARCHAR(255),
  shipping_same_as_billing BOOLEAN,
  shipping_address_line1 VARCHAR(255),
  shipping_address_line2 VARCHAR(255),
  shipping_city VARCHAR(255),
  shipping_state VARCHAR(255),
  shipping_pincode VARCHAR(255),
  shipping_country VARCHAR(255),
  business_type VARCHAR(255),
  industry VARCHAR(255),
  gstin VARCHAR(255),
  pan_number VARCHAR(255),
  aadhar_number VARCHAR(255),
  bank_name VARCHAR(255),
  bank_account_number VARCHAR(255),
  bank_ifsc_code VARCHAR(255),
  bank_branch VARCHAR(255),
  credit_limit DECIMAL(18,2),
  payment_terms VARCHAR(255),
  currency VARCHAR(255),
  project_area VARCHAR(255),
  notes TEXT,
  is_active BOOLEAN,
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  company_id BIGINT,
  created_by_id BIGINT,
  gst_registration_date DATE,
  is_gst_registered BOOLEAN,
  state_code VARCHAR(255),
  account_holder_name VARCHAR(255),
  bank_verification_status VARCHAR(255),
  bank_verified_date TIMESTAMP,
  last_statement_import TIMESTAMP,
  statement_import_enabled BOOLEAN,
  opening_balance DECIMAL(18,2),
  opening_balance_date DATE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE finance_invoices (
  id BIGINT PRIMARY KEY,
  invoice_number VARCHAR(255),
  invoice_date DATE,
  due_date DATE,
  reference VARCHAR(255),
  customer_gstin VARCHAR(255),
  company_gstin VARCHAR(255),
  gst_type VARCHAR(255),
  subtotal DECIMAL(18,2),
  total_tax DECIMAL(18,2),
  total_amount DECIMAL(18,2),
  cgst_amount DECIMAL(18,2),
  sgst_amount DECIMAL(18,2),
  igst_amount DECIMAL(18,2),
  discount_percentage DECIMAL(18,2),
  discount_amount DECIMAL(18,2),
  shipping_charges DECIMAL(18,2),
  other_charges DECIMAL(18,2),
  payment_status VARCHAR(255),
  paid_amount DECIMAL(18,2),
  outstanding_amount DECIMAL(18,2),
  last_payment_date DATE,
  payment_due_date DATE,
  invoice_type VARCHAR(255),
  status VARCHAR(255),
  notes TEXT,
  terms_and_conditions TEXT,
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  company_id BIGINT,
  created_by_id BIGINT,
  customer_id BIGINT,
  shipping_address_id BIGINT,
  proforma_invoice_id BIGINT,
  purchase_order_id BIGINT,
  gst_transaction_id VARCHAR(255),
  gstr1_filing_date DATE,
  is_filed_in_gstr1 BOOLEAN,
  place_of_supply VARCHAR(255),
  reverse_charge_applicable BOOLEAN,
  quotation_id BIGINT,
  is_rejected BOOLEAN,
  rejected_at TIMESTAMP,
  rejected_by_id BIGINT,
  rejection_reason TEXT,
  is_revised BOOLEAN,
  revised_at TIMESTAMP,
  revised_by_id BIGINT,
  revision_count INT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE finance_purchase_orders (
  id BIGINT PRIMARY KEY,
  po_number VARCHAR(255),
  po_date DATE,
  po_file VARCHAR(255),
  internal_po_number VARCHAR(255),
  quotation_date DATE,
  valid_until DATE,
  reference VARCHAR(255),
  gst_type VARCHAR(255),
  customer_gstin VARCHAR(255),
  company_gstin VARCHAR(255),
  subtotal DECIMAL(18,2),
  total_tax DECIMAL(18,2),
  total_amount DECIMAL(18,2),
  cgst_amount DECIMAL(18,2),
  sgst_amount DECIMAL(18,2),
  igst_amount DECIMAL(18,2),
  discount_percentage DECIMAL(18,2),
  discount_amount DECIMAL(18,2),
  shipping_charges DECIMAL(18,2),
  other_charges DECIMAL(18,2),
  status VARCHAR(255),
  notes TEXT,
  terms_and_conditions TEXT,
  claim_type VARCHAR(255),
  proforma_claimed_amount DECIMAL(18,2),
  invoice_claimed_amount DECIMAL(18,2),
  remaining_proforma_balance DECIMAL(18,2),
  remaining_invoice_balance DECIMAL(18,2),
  proforma_status VARCHAR(255),
  invoice_status VARCHAR(255),
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  company_id BIGINT,
  created_by_id BIGINT,
  customer_id BIGINT,
  shipping_address_id BIGINT,
  quotation_id BIGINT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE finance_payments (
  id BIGINT PRIMARY KEY,
  payment_number VARCHAR(255),
  payment_date DATE,
  amount DECIMAL(18,2),
  payment_method VARCHAR(255),
  tds_amount DECIMAL(18,2),
  tds_percentage DECIMAL(18,2),
  tds_section VARCHAR(255),
  net_amount_received DECIMAL(18,2),
  tds_certificate_number VARCHAR(255),
  tds_certificate_date DATE,
  is_tds_received BOOLEAN,
  reference_number VARCHAR(255),
  transaction_id VARCHAR(255),
  bank_name VARCHAR(255),
  status VARCHAR(255),
  notes TEXT,
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  company_id BIGINT,
  created_by_id BIGINT,
  customer_id BIGINT,
  invoice_id BIGINT,
  proforma_invoice_id BIGINT,
  purchase_order_id BIGINT,
  form16a_number VARCHAR(255),
  tds_certificate_issued BOOLEAN,
  tds_challan_number VARCHAR(255),
  tds_deposited_date DATE,
  tds_rate_applied DECIMAL(18,2),
  tds_section_code VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE finance_quotations (
  id BIGINT PRIMARY KEY,
  quotation_number VARCHAR(255),
  quotation_date DATE,
  valid_until DATE,
  reference VARCHAR(255),
  gst_type VARCHAR(255),
  customer_gstin VARCHAR(255),
  company_gstin VARCHAR(255),
  subtotal DECIMAL(18,2),
  total_tax DECIMAL(18,2),
  total_amount DECIMAL(18,2),
  cgst_amount DECIMAL(18,2),
  sgst_amount DECIMAL(18,2),
  igst_amount DECIMAL(18,2),
  discount_percentage DECIMAL(18,2),
  discount_amount DECIMAL(18,2),
  shipping_charges DECIMAL(18,2),
  other_charges DECIMAL(18,2),
  status VARCHAR(255),
  notes TEXT,
  terms_and_conditions TEXT,
  is_revised BOOLEAN,
  revision_count INT,
  revised_at TIMESTAMP,
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  company_id BIGINT,
  created_by_id BIGINT,
  customer_id BIGINT,
  revised_by_id BIGINT,
  shipping_address_id BIGINT,
  invoice_created BOOLEAN,
  invoice_created_at TIMESTAMP,
  po_created BOOLEAN,
  po_created_at TIMESTAMP,
  claim_type VARCHAR(255),
  invoice_claimed_amount DECIMAL(18,2),
  proforma_claimed_amount DECIMAL(18,2),
  remaining_invoice_balance DECIMAL(18,2),
  remaining_proforma_balance DECIMAL(18,2),
  proforma_created BOOLEAN,
  is_rejected BOOLEAN,
  rejected_at TIMESTAMP,
  rejected_by_id BIGINT,
  rejection_reason TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;